Dclaxton6/27 create npc tab
cstewart2010/pta-frontend pull request #32
Opened 2022-04-25 19:25 UTC by dclaxton6

2022-04-30 19:40 UTC, cstewart2010 requested changes

2022-04-30 19:40 UTC, cstewart2010 commented on src/views/Npcs.vue
> +<template>
We don't need this file anymore.

2022-04-30 19:40 UTC, cstewart2010 commented on src/components/npcs/incompleteNpc.vue
> +<template>
Fix this file name: IncompleteNpc.vue

2022-05-02 00:42 UTC, dclaxton6 commented on src/components/npcs/incompleteNpc.vue
> +<template>
done

2022-05-02 00:46 UTC, cstewart2010 approved these changes

2022-05-02 00:46 UTC, merged